# Generated by Django 3.1.2 on 2021-08-23 05:22

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知作成日時')),
                ('title', models.CharField(max_length=200, verbose_name='通知タイトル')),
                ('content', models.CharField(max_length=2000, verbose_name='通知内容')),
            ],
            options={
                'db_table': 'notify',
            },
        ),
        migrations.CreateModel(
            name='NotifyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='通知カテゴリ名')),
            ],
            options={
                'db_table': 'notify_category',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('title', models.CharField(max_length=50, verbose_name='動画タイトル')),
                ('description', models.CharField(max_length=300, verbose_name='動画説明文')),
                ('content', models.FileField(upload_to='tube/video/', verbose_name='動画')),
                ('thumbnail', models.ImageField(blank=True, upload_to='tube/thumbnail/', verbose_name='サムネイル')),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='再生回数')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='動画カテゴリ名')),
            ],
            options={
                'db_table': 'video_category',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('content', models.CharField(max_length=200, verbose_name='コメント')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='コメント先の動画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'video_comment',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tube.videocategory', verbose_name='動画カテゴリ'),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.CreateModel(
            name='NotifyTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知日時')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.notify', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='通知対象')),
            ],
            options={
                'db_table': 'notify_target',
                'unique_together': {('user', 'notify')},
            },
        ),
        migrations.AddField(
            model_name='notify',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.notifycategory', verbose_name='通知カテゴリ'),
        ),
        migrations.AddField(
            model_name='notify',
            name='target',
            field=models.ManyToManyField(through='tube.NotifyTarget', to=settings.AUTH_USER_MODEL, verbose_name='通知対象のユーザー'),
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='マイリスト動画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録したユーザー')),
            ],
            options={
                'db_table': 'mylist',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='視聴日時')),
                ('views', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='視聴回数')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='視聴した動画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='視聴したユーザー')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='GoodVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='評価日時')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='対象動画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='高評価したユーザー')),
            ],
            options={
                'db_table': 'good_video',
            },
        ),
        migrations.CreateModel(
            name='BadVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='評価日時')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='対象動画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='低評価したユーザー')),
            ],
            options={
                'db_table': 'bad_video',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='実行日')),
                ('play', models.IntegerField(verbose_name='再生点')),
                ('mylist', models.IntegerField(verbose_name='マイリスト点')),
                ('good', models.IntegerField(verbose_name='良いね点')),
                ('bad', models.IntegerField(verbose_name='悪いね点')),
                ('comment', models.IntegerField(verbose_name='コメント点')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tube.videocategory', verbose_name='動画カテゴリ')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='対象動画')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='実行したユーザー')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
