# Generated by Django 3.1.2 on 2021-08-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BadVideo',
            new_name='VideoBad',
        ),
        migrations.RenameModel(
            old_name='GoodVideo',
            new_name='VideoGood',
        ),
        migrations.AddField(
            model_name='video',
            name='bad',
            field=models.ManyToManyField(related_name='video_bad', through='tube.VideoBad', to=settings.AUTH_USER_MODEL, verbose_name='悪いね'),
        ),
        migrations.AddField(
            model_name='video',
            name='good',
            field=models.ManyToManyField(related_name='video_good', through='tube.VideoGood', to=settings.AUTH_USER_MODEL, verbose_name='良いね'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tube.videocategory', verbose_name='実行時の動画カテゴリ'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_user', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
