# Generated by Django 3.1.2 on 2021-08-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20210825_1502'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videobad',
            table='video_bad',
        ),
        migrations.AlterModelTable(
            name='videogood',
            table='video_good',
        ),
    ]
