# Generated by Django 3.1.2 on 2021-08-25 06:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0003_auto_20210825_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='VideoHistory',
        ),
        migrations.RenameModel(
            old_name='MyList',
            new_name='VideoMyList',
        ),
    ]
