# Generated by Django 3.1.2 on 2021-08-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_auto_20210825_1507'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videohistory',
            table='video_history',
        ),
        migrations.AlterModelTable(
            name='videomylist',
            table='video_mylist',
        ),
    ]
