# Generated by Django 3.1.2 on 2021-08-25 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0005_auto_20210825_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.ManyToManyField(related_name='video_comment', through='tube.VideoComment', to=settings.AUTH_USER_MODEL, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='video',
            name='history',
            field=models.ManyToManyField(related_name='video_history', through='tube.VideoHistory', to=settings.AUTH_USER_MODEL, verbose_name='視聴履歴'),
        ),
        migrations.AddField(
            model_name='video',
            name='mylist',
            field=models.ManyToManyField(related_name='video_mylist', through='tube.VideoMyList', to=settings.AUTH_USER_MODEL, verbose_name='マイリスト'),
        ),
    ]
