# Generated by Django 3.1.2 on 2021-08-26 02:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0006_auto_20210825_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='再生日')),
                ('ip', models.GenericIPAddressField(verbose_name='再生した人のIPアドレス')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='再生する動画')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='再生した人')),
            ],
            options={
                'db_table': 'video_view',
                'unique_together': {('date', 'user'), ('date', 'ip')},
            },
        ),
    ]
