# Generated by Django 3.1.2 on 2021-08-26 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0007_auto_20210826_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.ManyToManyField(related_name='video_view', through='tube.VideoView', to=settings.AUTH_USER_MODEL, verbose_name='再生'),
        ),
    ]
