# Generated by Django 3.1.2 on 2021-08-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_auto_20210826_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoview',
            unique_together={('target', 'date', 'ip')},
        ),
    ]
