# Generated by Django 3.1.2 on 2021-08-26 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0011_auto_20210826_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoview',
            unique_together={('target', 'date', 'ip'), ('target', 'date', 'user')},
        ),
    ]
