# Generated by Django 3.1.2 on 2021-08-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0012_auto_20210826_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='view',
        ),
    ]
