# Generated by Django 3.1.2 on 2021-08-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0015_auto_20210826_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='date',
            field=models.DateField(verbose_name='再生日'),
        ),
    ]
