# Generated by Django 3.1.2 on 2021-08-30 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0017_auto_20210826_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='ニュースカテゴリ')),
            ],
            options={
                'db_table': 'news_category',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.ManyToManyField(related_name='video_view', through='tube.VideoView', to=settings.AUTH_USER_MODEL, verbose_name='再生'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('start_dt', models.DateField(verbose_name='カルーセル掲示期間(開始日)')),
                ('end_dt', models.DateField(verbose_name='カルーセル掲示期間(終了日)')),
                ('title', models.CharField(max_length=200, verbose_name='ニュースタイトル')),
                ('content', models.CharField(max_length=2000, verbose_name='ニュース内容')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tube.newscategory', verbose_name='ニュースカテゴリ')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
