# Generated by Django 3.1.2 on 2021-08-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0018_auto_20210830_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='end_dt',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='start_dt',
            new_name='start_date',
        ),
    ]
