# Generated by Django 3.1.2 on 2021-10-02 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0019_auto_20210830_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMyListFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('title', models.CharField(max_length=50, verbose_name='フォルダタイトル')),
                ('description', models.CharField(max_length=300, verbose_name='フォルダ説明文')),
                ('public', models.BooleanField(default=False, verbose_name='フォルダ公開設定')),
                ('search', models.BooleanField(default=False, verbose_name='検索表示設定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='フォルダ所有者')),
            ],
            options={
                'db_table': 'video_mylist_folder',
            },
        ),
        migrations.AddField(
            model_name='videomylist',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.videomylistfolder', verbose_name='所属フォルダ'),
        ),
    ]
