# Generated by Django 3.1.2 on 2021-10-02 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0020_auto_20211002_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500, verbose_name='質問')),
                ('answer', models.CharField(max_length=500, verbose_name='回答')),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='問い合わせ日時')),
                ('content', models.CharField(max_length=1000, verbose_name='お問い合わせ内容')),
                ('ip', models.GenericIPAddressField(verbose_name='お問い合わせした端末のIPアドレス')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='お問い合わせしたユーザー')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
