# Generated by Django 3.1.2 on 2021-11-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tube', '0021_contact_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser', verbose_name='設定したユーザー')),
                ('appear_news', models.BooleanField(default=False, verbose_name='ニュースを表示')),
            ],
        ),
    ]
