# Generated by Django 3.1.2 on 2021-11-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0022_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='search_amount',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='検索表示件数'),
        ),
    ]
